project:
  type: website

website:
  title: "StatsData Hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: browse.qmd
        text: Browse Datasets
      - href: r-package.qmd
        text: R Package
      - href: contribute.qmd
        text: Contribute

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true